### ISSUE TITLE
Exception can occur

### ISSUE THREAD

**Issue by remag9330** [remag9330/camera-streamer#18]
Looks like 2 exceptions are happening at once on separate threads and are intertwining on the output, but looks like it's a combination of #17 and something else (maybe an issue with bottle?)

```
Traceback (most recent call last):
  File "C:\Users\***\Desktop\camera-streamer-master-1.1\src\recorder.py", line 105, in callback
Traceback (most recent call last):
  File "C:\Users\***\Desktop\camera-streamer-master-1.1\src\main.py", line 12, in <module>
    webserver.start_listening()
  File "C:\Users\***\Desktop\camera-streamer-master-1.1\src\webserver.py", line 9, in start_listening
    self.outfile.writeframes(in_data)
  File "C:\Program Files (x86)\Python37-32\lib\wave.py", line 438, in writeframes
    run(host="0.0.0.0", port=8080, debug=True, quiet=True)
  File "C:\Users\***\Desktop\camera-streamer-master-1.1\env\lib\site-packages\bottle.py", line 3137, in run
    self.writeframesraw(data)
  File "C:\Program Files (x86)\Python37-32\lib\wave.py", line 433, in writeframesraw
    self._file.write(data)
AttributeError: 'NoneType' object has no attribute 'write'
    server.run(app)
  File "C:\Users\***\Desktop\camera-streamer-master-1.1\env\lib\site-packages\bottle.py", line 2790, in run
    srv.serve_forever()
  File "C:\Program Files (x86)\Python37-32\lib\socketserver.py", line 232, in serve_forever
    ready = selector.select(poll_interval)
  File "C:\Program Files (x86)\Python37-32\lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Program Files (x86)\Python37-32\lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
AttributeError
sys:1: ResourceWarning: unclosed <socket.socket fd=2880, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8080)>
```

**Comment by remag9330** [comment]
See if this keeps happening after the fix for related issue, but leaving open for now

**Comment by remag9330** [comment]
Haven't seen this for a while, so closing out for now
